export const rows =[
    {
        id:'1',
        employmentType:'full time',
        companyName:'google',
        salary:20000,
        dataPosted:'20/9/23',
        position:'junior developer',
        contactPerson:'ryan',
        contacNumber:'1234567',
        contactEmail:'ryan@gmail.com',
        requirements:'2 years',
        isArchive:true,
    },{
        id:'2',
        employmentType:'full time',
        companyName:'google',
        salary:20000,
        dataPosted:'20/9/23',
        position:'junior developer',
        contactPerson:'ryan',
        contacNumber:'1234567',
        contactEmail:'ryan@gmail.com',
        requirements:'2 years',
        isArchive:true,
    },{
        id:'3',
        employmentType:'full time',
        companyName:'google',
        salary:20000,
        dataPosted:'20/9/23',
        position:'junior developer',
        contactPerson:'ryan',
        contacNumber:'1234567',
        contactEmail:'ryan@gmail.com',
        requirements:'2 years',
        isArchive:true,
    },{
        id:'4',
        employmentType:'full time',
        companyName:'google',
        salary:20000,
        dataPosted:'20/9/23',
        position:'junior developer',
        contactPerson:'ryan',
        contacNumber:'1234567',
        contactEmail:'ryan@gmail.com',
        requirements:'2 years',
        isArchive:true,
    },{
        id:'5',
        employmentType:'full time',
        companyName:'google',
        salary:20000,
        dataPosted:'20/9/23',
        position:'junior developer',
        contactPerson:'ryan',
        contacNumber:'1234567',
        contactEmail:'ryan@gmail.com',
        requirements:'2 years',
        isArchive:true,
    },{
        id:'6',
        employmentType:'full time',
        companyName:'google',
        salary:20000,
        dataPosted:'20/9/23',
        position:'junior developer',
        contactPerson:'ryan',
        contacNumber:'1234567',
        contactEmail:'ryan@gmail.com',
        requirements:'2 years',
        isArchive:true,
    },{
        id:'7',
        employmentType:'full time',
        companyName:'google',
        salary:20000,
        dataPosted:'20/9/23',
        position:'junior developer',
        contactPerson:'ryan',
        contacNumber:'1234567',
        contactEmail:'ryan@gmail.com',
        requirements:'2 years',
        isArchive:true,
    }
]