export const rows =[
    {
        id:'1',
        companyName:'apple',
        annualSalary:300000,
        title:'junior programmer',
        workLocationArrangement:'bus',
        requirements:'2 years',
        monthFromGraduation:12 ,
    },{
        id:'2',
        companyName:'apple',
        annualSalary:300000,
        title:'junior programmer',
        workLocationArrangement:'bus',
        requirements:'2 years',
        monthFromGraduation:12 ,
    },{
        id:'3',
        companyName:'apple',
        annualSalary:300000,
        title:'junior programmer',
        workLocationArrangement:'bus',
        requirements:'2 years',
        monthFromGraduation:12 ,
    },{
        id:'4',
        companyName:'apple',
        annualSalary:300000,
        title:'junior programmer',
        workLocationArrangement:'bus',
        requirements:'2 years',
        monthFromGraduation:12 ,
    },{
        id:'5',
        companyName:'apple',
        annualSalary:300000,
        title:'junior programmer',
        workLocationArrangement:'bus',
        requirements:'2 years',
        monthFromGraduation:12 ,
    },{
        id:'6',
        companyName:'apple',
        annualSalary:300000,
        title:'junior programmer',
        workLocationArrangement:'bus',
        requirements:'2 years',
        monthFromGraduation:12 ,
    },{
        id:'7',
        companyName:'apple',
        annualSalary:300000,
        title:'junior programmer',
        workLocationArrangement:'bus',
        requirements:'2 years',
        monthFromGraduation:12 ,
    }
]